project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!isabelle-m08-reflection.qmd"
    - "!isabelle-m12-reflection.qmd"
    - "!rendered/**"
  resources:
    - "rendered/**"

website:
  title: "Isabelle Garza Portfolio"
  navbar:
    title: "Isabelle Garza"
    left:
      - href: index.qmd
        text: Home
      - href: coursework.qmd
        text: Coursework
      - href: projects.qmd
        text: Projects
      - text: Data Science
        menu:
          - href: data-viz.qmd
            text: Data Visualization
          - href: advanced-viz.qmd
            text: Advanced Visualization
          - href: data-wrangling.qmd
            text: Data Wrangling
          - href: r-programming.qmd
            text: R Programming
      - href: marketing-projects.qmd
        text: Marketing
      - href: certifications.qmd
        text: Certifications
      - href: google-analytics.qmd
        text: Analytics
      - href: presentations.qmd
        text: Revealjs Presentations
      - href: resume.qmd
        text: Resume
      - href: about.qmd
        text: About
    right:
      - icon: envelope
        href: mailto:izzygarza5@gmail.com
      - icon: linkedin
        href: https://www.linkedin.com/in/isabelle-garza-65b3262a4/
      - icon: github
        href: https://github.com/izzygarza5-rgb

format:
  html:
    theme:
      - flatly
    css: styles.css
    toc: false
